### PR TITLE
Add support for the keyboard

### LINKED ISSUE #1: Keyboard support
This project looks very cool, though it unfortunately does not support keyboard led control.

As described in the Aura SDK FAQ at https://www.asus.com/campaign/aura/us/SDK.html, Aura SDK also has support for keyboards (and mice), while this project only supports motherboard, GPU and DRAM control. Please see if it is possible to add a controller for keyboards (mice would of course be nice too, though not relevant in my case).

### PR DESCRIPTION
**Pull request by DanielRamosAcosta**
Fixes #1

@enteryournamehere, @kekkokk could you try this branch? I don't have a ROG keyboard so I can't check this is working.

Please, execute the [`example/rainbow.js`](https://github.com/DanielRamosAcosta/aura-sdk/blob/keyboard-support/example/rainbow.js#L17) and see if it works.

```
git clone git@github.com:DanielRamosAcosta/aura-sdk.git
cd aura-sdk
git checkout keyboard-support
```

Download ASUS SDK and place it in the root of the working directory, so it remains like this: https://i.imgur.com/rH9dXna.png

```
npm install
npm run compile:cpp
npm run compile:ts
node ./example/rainbow.js
```

### CODE REVIEW

**Comment by enteryournamehere** [comment]
Thank you, will try it ASAP when I'm home (next 24 hours)

**Comment by kekkokk** [comment]
Nope I cannot make it to run

`C:\Users\Duri\Desktop\aura-sdk-keyboard-support>node example\rainbow.js
DRAM controller isn't supported
Entering setupKeyboard
I'm going to execute createClaymoreKeyboard

C:\Users\Duri\Desktop\aura-sdk-keyboard-support>`

Also including ClaymoreProtocol.dll (which is absolutely needed btw) no way to reach

>         printf("All ended OK\n");

**Comment by DanielRamosAcosta** [comment]
Didn't know about that DLL, I'll try it when I arrive home

**Comment by DanielRamosAcosta** [comment]
I managed to get it working! It's the same that with the GPU, the DLL has to be in the CWD.

**Comment by DanielRamosAcosta** [comment]
Could you pull and try again plase @enteryournamehere , @kekkokk?

**Comment by kekkokk** [comment]
Ok so, running example, it seems it can take the control of the keyboard since it turns black when launching script but no colors are displayed

**Comment by DanielRamosAcosta** [comment]
I've added some log, can you share the output?

**Comment by kekkokk** [comment]
yeah, this evening after work

**Comment by enteryournamehere** [comment]
I am getting this:
```
(...)\aura-sdk> node example\rainbow.js
warning: controllerCountMb < 1
DRAM controller isn't supported
warning: controllerCountKeyboard < 1
```
I do have a compatible keyboard, as far as I know - I have a ROG Strix GL503VD-FY127T with an [Aura rgb keyboard](https://i.imgur.com/6L7STT5.png).

[Here](https://imgur.com/2tAWGBu.png) is the output from `npm install`, maybe those warnings have something to do with it? (of course I can paste the output here if you want)

**Comment by DanielRamosAcosta** [comment]
@enteryournamehere That's an error that happens sometimes to me... Can you try changing the color with Aura software, and then execute the script again?

**Comment by enteryournamehere** [comment]
I've changed the colour with Aura software but the script still gives the same error.

**Comment by DanielRamosAcosta** [comment]
I've no idea 😢. Sorry but I don't have that keyboard to test...

**Pull request closed without merging**
